/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package a.ceasar;

/**
 *
 * @author Asus
 */
public class Ceasarr extends javax.swing.JFrame {

    /**
     * Creates new form Ceasarr
     */
    public Ceasarr() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btMaHoa = new javax.swing.JButton();
        btGiaiMa = new javax.swing.JButton();
        txtBanRo = new javax.swing.JTextField();
        txtKhoa = new javax.swing.JTextField();
        txtBanMa = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Thuật Toán Ceasar");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Bản rõ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Khóa");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Bản mã");

        btMaHoa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btMaHoa.setText("Mã hóa");
        btMaHoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMaHoaActionPerformed(evt);
            }
        });

        btGiaiMa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btGiaiMa.setText("Giải mã");
        btGiaiMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGiaiMaActionPerformed(evt);
            }
        });

        txtBanRo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtBanRo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBanRoActionPerformed(evt);
            }
        });

        txtKhoa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtBanMa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton3.setText("Open file");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtBanRo)
                                    .addComponent(txtKhoa)
                                    .addComponent(txtBanMa, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btMaHoa)
                        .addGap(41, 41, 41)
                        .addComponent(btGiaiMa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(31, 31, 31))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtBanRo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(jLabel3))
                    .addComponent(txtKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(txtBanMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btMaHoa)
                    .addComponent(btGiaiMa)
                    .addComponent(jButton3))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBanRoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBanRoActionPerformed
                // TODO add your handling code here:
                
    }//GEN-LAST:event_txtBanRoActionPerformed
    // Button Mã Hóa
    private void btMaHoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMaHoaActionPerformed
        // TODO add your handling code here:
        int k = Integer.parseInt(txtKhoa.getText());
        String banro = txtBanRo.getText();
        String banma = "";
        int n = banro.length();
        for(int i =0; i< n; i++){
            banma+= mahoa(banro.charAt(i), k);
        }
        txtBanMa.setText(banma);
        //System.out.println(banma);
    }//GEN-LAST:event_btMaHoaActionPerformed
    //Button Phá Mã
    private void btGiaiMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGiaiMaActionPerformed
        // TODO add your handling code here:
        int k = Integer.parseInt(txtKhoa.getText());
        String banma = txtBanMa.getText();
        String banro = "";
        int n = banma.length();
        for(int i =0; i< n; i++){
            banro+= phama(banma.charAt(i), k);
        }
        txtBanRo.setText(banro);
    }//GEN-LAST:event_btGiaiMaActionPerformed
    
    // Hàm mã hóa
    char mahoa(char c, int k){
        return (char) ((((Character.toUpperCase(c)- 'A')+k)%26 +26 ) %26+'A');
    }
    // Hàm phá mã
    char phama(char q, int k){
return (char) (((Character.toUpperCase(q)- 'A')-(k%26)+26)%26 +'A');
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGiaiMa;
    private javax.swing.JButton btMaHoa;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtBanMa;
    private javax.swing.JTextField txtBanRo;
    private javax.swing.JTextField txtKhoa;
    // End of variables declaration//GEN-END:variables
}
